<a href="https://colab.research.google.com/github/tusharpamnani/DL-Lab/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

2A. Implement Perceptron Learning Algorithm for classification of following points <br/>
{P0(-1,-1,-1), P1(-1,-1,1), P2(-1,1,-1), P3(-1,1,1), P4(1,-1,-1), P5(1,-1,1), P6(1,1,-1), P7(1,1,1)}<br/> into two classes. <br/>
C1 = {P1(1,1,1)}<br/>
c2: {P0(-1,-1,-1), P1(-1,-1,1), P2(-1,1,-1), P3(-1,1,1), P4(1,-1,-1), P5(1,-1,1), P6(1,1,-1)}

Basic NAND Gate implementation

In [13]:
import numpy as np

In [9]:
def step(weighted_Sum, threshold) :
    if weighted_Sum >= threshold:
      return 0
    else:
      return 1

In [10]:
def nand_gate(inputs, weights):
  input_sum = 0
  threshold = 0
  bias = -3
  for i in range(len(inputs)):
    input_sum += inputs[i] * weights[i]
  return step(input_sum  + bias, threshold)

In [11]:
inputs = [[0,0,0], [0,0,1], [0,1,0], [0,1,1], [1,0,0], [1,0,1], [1,1,1]]
for i in inputs:
  weight = [1,1,1]
  op = nand_gate(i, weight)
  print(i, op)

[0, 0, 0] 1
[0, 0, 1] 1
[0, 1, 0] 1
[0, 1, 1] 1
[1, 0, 0] 1
[1, 0, 1] 1
[1, 1, 1] 0


Solving the Problem

In [21]:
data_points = {
      'P0': (-1,-1,-1),
      'P1': (-1,-1,1),
      'P2': (-1,1,-1),
      'P3': (-1,1,1),
      'P4': (1,-1,-1),
      'P5': (1,-1,1),
      'P6': (1,1,-1),
      'P7': (1,1,1)
    }

In [22]:
c1 = ['P7']
c2 = ['P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6']

In [23]:
weights = np.zeros(len(data_points['P0']))
bias = 0
print("Initail Weight: ", weights)

Initail Weight:  [0. 0. 0.]


In [24]:
learning_rate = 1

In [25]:
epochs = 100

In [37]:
X = np.array([[-1, -1, -1], [-1, -1, 1], [-1, 1, -1], [-1, 1, 1],
              [1, -1, -1], [1, -1, 1], [1, 1, -1], [1, 1, 1]])
y = np.array([0, 0, 0, 0, 0, 0, 0, 1])

In [39]:
w = np.zeros(3)

In [41]:
b = 0

In [42]:
for epoch in range(epochs):
    for i in range(len(X)):
        z = np.dot(X[i], w) + b
        prediction = 1 if z >= 0 else 0
        if prediction != y[i]:
            w = w + learning_rate * (y[i] - prediction) * X[i]
            b = b + learning_rate * (y[i] - prediction)

In [43]:
print("Learned weights:", w)
print("Learned bias:", b)

Learned weights: [1. 1. 1.]
Learned bias: -3


In [44]:
new_data_point = np.array([[-1,-1,-1],[-1,-1,1], [-1,1,-1], [-1,1,1],[1,-1,-1], [1,-1,1], [1,1,-1], [1,1,1]])

In [45]:
for i in new_data_point:
  z = np.dot(i, w) + b
  prediction = 0 if z >= 0 else 1
  print(i,prediction)

[-1 -1 -1] 1
[-1 -1  1] 1
[-1  1 -1] 1
[-1  1  1] 1
[ 1 -1 -1] 1
[ 1 -1  1] 1
[ 1  1 -1] 1
[1 1 1] 0
